[server]
# Enable file uploads
enableXsrfProtection = false
enableCORS = false

[browser]
# Set page title
gatherUsageStats = false

[theme]
# Custom theme for better appearance
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
